"""empty message

Revision ID: b2d1cd496a5f
Revises: f5ad65661371
Create Date: 2020-12-18 10:37:57.237449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d1cd496a5f'
down_revision = 'f5ad65661371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskline', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskline', 'done')
    # ### end Alembic commands ###
