"""empty message

Revision ID: f5ad65661371
Revises: 4220b1d3e7f4
Create Date: 2020-12-18 09:50:28.257665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ad65661371'
down_revision = '4220b1d3e7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskline',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['taskheader.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskline')
    # ### end Alembic commands ###
